#!/usr/bin/env python3
"""
Dr. Zero Self-Evolution Engine
Implements Proposer-Solver Co-Evolution Framework
Based on Meta/UIUC research: arXiv:2601.07055

Integrated with Claude Code autonomous agent system.
Runs automatically via hooks - no manual invocation needed.
"""

import json
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass, asdict
from enum import Enum

class Domain(Enum):
    TRADING = "trading"
    RESEARCH = "research"
    GENERAL = "general"
    CODING = "coding"
    DATA_ANALYSIS = "data_analysis"

@dataclass
class Challenge:
    """Represents a challenge generated by the Proposer"""
    id: str
    domain: str
    description: str
    hop_count: int
    tier: str  # "growth" or "aspirational"
    created_at: str
    solved: bool = False
    score: Optional[float] = None
    solution_approach: Optional[str] = None

@dataclass
class EvolutionState:
    """Tracks the evolution state for a domain"""
    domain: str
    iteration: int
    frontier_hop_level: int
    total_challenges: int
    solved_challenges: int
    group_baselines: Dict[int, float]  # hop_count -> baseline_score
    capability_gaps: List[str]
    strategy_portfolio: List[str]
    last_updated: str

class DrZeroEngine:
    """Core evolution engine implementing Proposer-Solver co-evolution"""

    def __init__(self, base_dir: str = "~/.claude/evolution"):
        self.base_dir = Path(base_dir).expanduser()
        self.state_dir = self.base_dir / "state"
        self.challenges_dir = self.base_dir / "challenges"

        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.challenges_dir.mkdir(parents=True, exist_ok=True)

    def load_state(self, domain: Domain) -> EvolutionState:
        """Load evolution state for a domain"""
        state_file = self.state_dir / f"{domain.value}_state.json"

        if state_file.exists():
            with open(state_file, 'r') as f:
                data = json.load(f)
                return EvolutionState(**data)
        else:
            # Initialize new state
            return EvolutionState(
                domain=domain.value,
                iteration=0,
                frontier_hop_level=1,
                total_challenges=0,
                solved_challenges=0,
                group_baselines={1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
                capability_gaps=[],
                strategy_portfolio=[],
                last_updated=datetime.now().isoformat()
            )

    def save_state(self, state: EvolutionState):
        """Save evolution state"""
        state_file = self.state_dir / f"{state.domain}_state.json"
        state.last_updated = datetime.now().isoformat()

        with open(state_file, 'w') as f:
            json.dump(asdict(state), f, indent=2)

    def load_challenges(self, domain: Domain) -> List[Challenge]:
        """Load all challenges for a domain"""
        challenges_file = self.challenges_dir / f"{domain.value}_challenges.json"

        if challenges_file.exists():
            with open(challenges_file, 'r') as f:
                data = json.load(f)
                return [Challenge(**c) for c in data]
        return []

    def save_challenges(self, domain: Domain, challenges: List[Challenge]):
        """Save challenges for a domain"""
        challenges_file = self.challenges_dir / f"{domain.value}_challenges.json"

        with open(challenges_file, 'w') as f:
            json.dump([asdict(c) for c in challenges], f, indent=2)

    def classify_task_domain(self, task_description: str, context: Dict) -> Optional[Domain]:
        """Classify what domain a task belongs to"""
        task_lower = task_description.lower()

        # Trading keywords
        trading_keywords = ['trade', 'strategy', 'market', 'stock', 'futures', 'forex',
                           'backtest', 'position', 'signal', 'cot', 'barometer']
        if any(kw in task_lower for kw in trading_keywords):
            return Domain.TRADING

        # Research keywords
        research_keywords = ['research', 'analyze', 'correlation', 'macro', 'intelligence',
                            'regime', 'capital flow', 'credit spread']
        if any(kw in task_lower for kw in research_keywords):
            return Domain.RESEARCH

        # Coding keywords
        coding_keywords = ['code', 'implement', 'debug', 'refactor', 'api', 'function',
                          'class', 'test', 'script']
        if any(kw in task_lower for kw in coding_keywords):
            return Domain.CODING

        # Data analysis keywords
        data_keywords = ['data', 'statistics', 'correlation', 'regression', 'cluster',
                        'visualization', 'pandas', 'numpy']
        if any(kw in task_lower for kw in data_keywords):
            return Domain.DATA_ANALYSIS

        return Domain.GENERAL

    def assess_complexity(self, task_description: str, context: Dict) -> int:
        """Estimate hop count (reasoning complexity) for a task"""
        # Simple heuristic based on task structure
        task_lower = task_description.lower()

        # Count reasoning indicators
        multi_step_indicators = ['and then', 'after that', 'followed by', 'next', 'subsequently']
        conditional_indicators = ['if', 'when', 'given', 'assuming', 'depending on']
        synthesis_indicators = ['combine', 'integrate', 'synthesize', 'correlate', 'compare']

        complexity_score = 1  # Base

        if any(ind in task_lower for ind in multi_step_indicators):
            complexity_score += 1
        if any(ind in task_lower for ind in conditional_indicators):
            complexity_score += 1
        if any(ind in task_lower for ind in synthesis_indicators):
            complexity_score += 1

        # Count mentioned data sources or tools
        tools_count = len([t for t in context.get('available_tools', []) if t.lower() in task_lower])
        if tools_count > 2:
            complexity_score += 1

        return min(complexity_score, 5)  # Cap at 5 hops

    def should_trigger_evolution(self, domain: Domain, task_complexity: int) -> bool:
        """Decide if we should trigger an evolution cycle"""
        state = self.load_state(domain)

        # Trigger if:
        # 1. Task complexity is at or above current frontier
        # 2. Every 5 iterations regardless
        # 3. If we have capability gaps in this area

        if task_complexity >= state.frontier_hop_level:
            return True

        if state.iteration > 0 and state.iteration % 5 == 0:
            return True

        if state.capability_gaps:
            return True

        return False

    def generate_proposer_challenges(self, domain: Domain, state: EvolutionState,
                                     count: int = 3) -> List[Challenge]:
        """Generate new challenges at the frontier"""
        challenges = []
        current_frontier = state.frontier_hop_level

        # Generate challenges at current frontier and frontier+1
        for i in range(count):
            hop_level = current_frontier if i < count - 1 else current_frontier + 1
            tier = "growth" if hop_level == current_frontier else "aspirational"

            challenge_id = f"{domain.value}_{state.iteration}_{i}"

            # Domain-specific challenge templates
            description = self._generate_challenge_description(domain, hop_level, i)

            challenges.append(Challenge(
                id=challenge_id,
                domain=domain.value,
                description=description,
                hop_count=hop_level,
                tier=tier,
                created_at=datetime.now().isoformat()
            ))

        return challenges

    def _generate_challenge_description(self, domain: Domain, hop_level: int,
                                        index: int) -> str:
        """Generate domain-specific challenge descriptions"""
        templates = {
            Domain.TRADING: {
                1: "Identify current COT positioning extreme for a single futures contract",
                2: "Find confluence between COT positioning and credit spread movement",
                3: "Build multi-factor chain: commodity breakdown -> EM stress -> currency impact",
                4: "Design regime-aware strategy responding to yield curve + VIX + capital flows"
            },
            Domain.RESEARCH: {
                1: "Look up current value of a single macro indicator",
                2: "Compare current credit spreads to last 3 historical episodes",
                3: "Trace causal chain from PMI decline to equity drawdown via copper and DXY",
                4: "Identify current macro regime from yield curve + COT + flows + VIX configuration"
            },
            Domain.CODING: {
                1: "Write a simple function to fetch data from an API",
                2: "Build API integration with error handling and retry logic",
                3: "Design multi-service orchestration with health checks and failover",
                4: "Architect self-healing system with monitoring, auto-recovery, and alerts"
            },
            Domain.GENERAL: {
                1: "Complete a single-step task with one tool",
                2: "Chain two tools together to solve a problem",
                3: "Orchestrate multi-step workflow across several tools",
                4: "Design and execute complex multi-phase solution with branching logic"
            }
        }

        domain_templates = templates.get(domain, templates[Domain.GENERAL])
        return domain_templates.get(hop_level, "Complex multi-hop challenge")

    def compute_group_baselines(self, challenges: List[Challenge]) -> Dict[int, float]:
        """Compute baseline scores for each hop group (HRPO)"""
        hop_groups = {}

        for challenge in challenges:
            if challenge.solved and challenge.score is not None:
                if challenge.hop_count not in hop_groups:
                    hop_groups[challenge.hop_count] = []
                hop_groups[challenge.hop_count].append(challenge.score)

        baselines = {}
        for hop_level, scores in hop_groups.items():
            baselines[hop_level] = sum(scores) / len(scores) if scores else 0.0

        return baselines

    def check_escalation_threshold(self, challenges: List[Challenge],
                                   hop_level: int) -> bool:
        """Check if we should escalate to next hop level (70% success rule)"""
        hop_challenges = [c for c in challenges if c.hop_count == hop_level]

        if not hop_challenges:
            return False

        solved = [c for c in hop_challenges if c.solved]
        success_rate = len(solved) / len(hop_challenges)

        return success_rate > 0.70

    def record_solution(self, domain: Domain, challenge_id: str, score: float,
                       approach: str):
        """Record a solution to a challenge"""
        challenges = self.load_challenges(domain)

        for challenge in challenges:
            if challenge.id == challenge_id:
                challenge.solved = True
                challenge.score = score
                challenge.solution_approach = approach
                break

        self.save_challenges(domain, challenges)

    def run_evolution_cycle(self, domain: Domain) -> Dict:
        """Execute one complete evolution cycle"""
        state = self.load_state(domain)
        state.iteration += 1

        # PROPOSER: Generate new challenges
        new_challenges = self.generate_proposer_challenges(domain, state, count=3)

        # Load existing challenges
        all_challenges = self.load_challenges(domain)
        all_challenges.extend(new_challenges)

        # EVOLUTION: Compute baselines and check for escalation
        baselines = self.compute_group_baselines(all_challenges)
        state.group_baselines = baselines

        # Check if we should escalate frontier
        if self.check_escalation_threshold(all_challenges, state.frontier_hop_level):
            state.frontier_hop_level += 1

        # Update statistics
        state.total_challenges = len(all_challenges)
        state.solved_challenges = len([c for c in all_challenges if c.solved])

        # Save updated state and challenges
        self.save_state(state)
        self.save_challenges(domain, all_challenges)

        return {
            'iteration': state.iteration,
            'frontier': state.frontier_hop_level,
            'new_challenges': [asdict(c) for c in new_challenges],
            'baselines': baselines,
            'stats': {
                'total': state.total_challenges,
                'solved': state.solved_challenges,
                'success_rate': state.solved_challenges / state.total_challenges if state.total_challenges > 0 else 0
            }
        }

    def get_evolution_context(self, domain: Domain) -> str:
        """Generate evolution context for injection into LLM prompt"""
        state = self.load_state(domain)
        challenges = self.load_challenges(domain)

        # Get unsolved challenges at current frontier
        frontier_challenges = [
            c for c in challenges
            if not c.solved and c.hop_count == state.frontier_hop_level
        ]

        context = f"""
<dr-zero-evolution-context domain="{domain.value}">
Iteration: {state.iteration}
Frontier Hop Level: {state.frontier_hop_level}
Success Rate: {state.solved_challenges}/{state.total_challenges} ({(state.solved_challenges/state.total_challenges*100) if state.total_challenges > 0 else 0:.1f}%)

Group Baselines (HRPO):
{json.dumps(state.group_baselines, indent=2)}

Active Capability Gaps:
{chr(10).join('- ' + gap for gap in state.capability_gaps[:5])}

Unsolved Frontier Challenges:
{chr(10).join(f'- [{c.hop_count}-hop] {c.description}' for c in frontier_challenges[:3])}

Strategy Portfolio (Top techniques):
{chr(10).join('- ' + strategy for strategy in state.strategy_portfolio[:5])}
</dr-zero-evolution-context>
"""
        return context.strip()


# Singleton instance
_engine = None

def get_engine() -> DrZeroEngine:
    """Get or create the singleton evolution engine"""
    global _engine
    if _engine is None:
        _engine = DrZeroEngine()
    return _engine


def classify_and_evolve(task_description: str, context: Dict) -> Optional[str]:
    """
    Main entry point for hooks.
    Classifies task, decides if evolution should trigger, returns context if needed.
    """
    engine = get_engine()

    # Classify domain
    domain = engine.classify_task_domain(task_description, context)
    if not domain:
        return None

    # Assess complexity
    complexity = engine.assess_complexity(task_description, context)

    # Decide if we should trigger evolution
    if engine.should_trigger_evolution(domain, complexity):
        # Run evolution cycle
        cycle_result = engine.run_evolution_cycle(domain)

        # Return evolution context for injection
        return engine.get_evolution_context(domain)

    return None


def record_task_result(domain_str: str, task_desc: str, success: bool,
                      score: float, approach: str):
    """Record the result of a task (called from post-tool-use hook)"""
    engine = get_engine()
    domain = Domain(domain_str)

    # Try to match to an existing challenge
    challenges = engine.load_challenges(domain)
    state = engine.load_state(domain)

    # Find best matching challenge (simple keyword matching)
    best_match = None
    best_score = 0

    for challenge in challenges:
        if not challenge.solved:
            # Simple keyword overlap
            task_words = set(task_desc.lower().split())
            challenge_words = set(challenge.description.lower().split())
            overlap = len(task_words & challenge_words)

            if overlap > best_score:
                best_score = overlap
                best_match = challenge

    if best_match and best_score > 2:  # Reasonable match
        engine.record_solution(domain, best_match.id, score, approach)

    # Update strategy portfolio if successful
    if success and score > 7.0:
        if approach not in state.strategy_portfolio:
            state.strategy_portfolio.append(approach)
            engine.save_state(state)


if __name__ == "__main__":
    # CLI interface for manual testing
    import sys

    if len(sys.argv) < 2:
        print("Usage: dr_zero_engine.py [status|evolve|reset] [domain]")
        sys.exit(1)

    command = sys.argv[1]
    domain_str = sys.argv[2] if len(sys.argv) > 2 else "general"

    engine = get_engine()
    domain = Domain(domain_str)

    if command == "status":
        state = engine.load_state(domain)
        print(json.dumps(asdict(state), indent=2))

    elif command == "evolve":
        result = engine.run_evolution_cycle(domain)
        print(json.dumps(result, indent=2))

    elif command == "reset":
        state_file = engine.state_dir / f"{domain.value}_state.json"
        challenges_file = engine.challenges_dir / f"{domain.value}_challenges.json"
        state_file.unlink(missing_ok=True)
        challenges_file.unlink(missing_ok=True)
        print(f"Reset {domain.value} evolution state")

    else:
        print(f"Unknown command: {command}")
        sys.exit(1)
